export const imageMap = {
  Landfill: {
    L1: require('../../assets/Images/Landfill/L1.jpg'),
    L2: require('../../assets/Images/Landfill/L2.jpg'),
    L3: require('../../assets/Images/Landfill/L3.jpg'),
    L4: require('../../assets/Images/Landfill/L4.jpg'),
    L5: require('../../assets/Images/Landfill/L5.jpg'),
    L6: require('../../assets/Images/Landfill/L6.jpg'),
    L7: require('../../assets/Images/Landfill/L7.jpg'),
    L8: require('../../assets/Images/Landfill/L8.jpg'),
    L9: require('../../assets/Images/Landfill/L9.jpg'),
    L10: require('../../assets/Images/Landfill/L10.jpg'),
  },
  Compost: {
    C1: require('../../assets/Images/Compost/C1.jpg'),
    C2: require('../../assets/Images/Compost/C2.jpg'),
    C3: require('../../assets/Images/Compost/C3.jpg'),
    C4: require('../../assets/Images/Compost/C4.jpg'),
    C5: require('../../assets/Images/Compost/C5.jpg'),
    C6: require('../../assets/Images/Compost/C6.jpg'),
    C7: require('../../assets/Images/Compost/C7.jpg'),
    C8: require('../../assets/Images/Compost/C8.jpg'),
    C9: require('../../assets/Images/Compost/C9.jpg'),
    C10: require('../../assets/Images/Compost/C10.jpg'),
  },
  Recycle: {
    R1: require('../../assets/Images/Recycle/R1.jpg'),
    R2: require('../../assets/Images/Recycle/R2.jpg'),
    R3: require('../../assets/Images/Recycle/R3.jpg'),
    R4: require('../../assets/Images/Recycle/R4.jpg'),
    R5: require('../../assets/Images/Recycle/R5.jpg'),
    R6: require('../../assets/Images/Recycle/R6.jpg'),
    R7: require('../../assets/Images/Recycle/R7.jpg'),
    R8: require('../../assets/Images/Recycle/R8.jpg'),
    R9: require('../../assets/Images/Recycle/R9.jpg'),
    R10: require('../../assets/Images/Recycle/R10.jpg'),
  },
  Paper: {
    P1: require('../../assets/Images/Paper/P1.jpg'),
    P2: require('../../assets/Images/Paper/P2.jpg'),
    P3: require('../../assets/Images/Paper/P3.jpg'),
    P4: require('../../assets/Images/Paper/P4.jpg'),
    P5: require('../../assets/Images/Paper/P5.jpg'),
    P6: require('../../assets/Images/Paper/P6.jpg'),
    P7: require('../../assets/Images/Paper/P7.jpg'),
    P8: require('../../assets/Images/Paper/P8.jpg'),
    P9: require('../../assets/Images/Paper/P9.jpg'),
    P10: require('../../assets/Images/Paper/P10.jpg'),
  },
};
